CMAKE_MINIMUM_REQUIRED(VERSION 3.15)
PROJECT(mttlib LANGUAGES CXX)

GET_FILENAME_COMPONENT(PARENT_DIR "${CMAKE_CURRENT_SOURCE_DIR}" DIRECTORY)
SET(EXPORT_LIB_DIR "${PARENT_DIR}/lib")

FILE(GLOB MTTP_SOURCES "src/*.cc")
FILE(GLOB TEST_SOURCES "tests/test-1.cc")

ADD_LIBRARY(mttlib STATIC ${MTTP_SOURCES})

TARGET_INCLUDE_DIRECTORIES(mttlib PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
)

TARGET_COMPILE_FEATURES(mttlib PUBLIC cxx_std_23) # /std:c++latest

if (MSVC)
  TARGET_COMPILE_OPTIONS(mttlib PRIVATE
    /utf-8
    /W4
    $<$<CONFIG:Debug>:/Zi /Od /MDd>
    $<$<CONFIG:Release>:/O2 /MD>
  )
endif ()

SET_TARGET_PROPERTIES(mttlib PROPERTIES
  ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_BINARY_DIR}/bin/debug"
  ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}/bin/release"
  OUTPUT_NAME "mttlib"
)

EXPORT(TARGETS mttlib
  NAMESPACE mttlib::
  FILE "${EXPORT_LIB_DIR}/mttlib-config.cmake"
)

ADD_EXECUTABLE(test-1 ${TEST_SOURCES})
TARGET_LINK_LIBRARIES(test-1 PRIVATE mttlib)

SET_TARGET_PROPERTIES(test-1 PROPERTIES
  RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_BINARY_DIR}/bin/debug"
  RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}/bin/release"
)